-- MySQL Script generated by MySQL Workbench
-- 2018年04月24日 星期二 17时10分58秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema yuanshiceping
-- -----------------------------------------------------
-- 远识测评

-- -----------------------------------------------------
-- Schema yuanshiceping
--
-- 远识测评
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yuanshiceping` DEFAULT CHARACTER SET utf8 ;
USE `yuanshiceping` ;

-- -----------------------------------------------------
-- Table `yuanshiceping`.`qualities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yuanshiceping`.`qualities` ;

CREATE TABLE IF NOT EXISTS `yuanshiceping`.`qualities` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `sort` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = '素质';


-- -----------------------------------------------------
-- Table `yuanshiceping`.`abilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yuanshiceping`.`abilities` ;

CREATE TABLE IF NOT EXISTS `yuanshiceping`.`abilities` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `sort` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = '才干，能力';


-- -----------------------------------------------------
-- Table `yuanshiceping`.`interests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yuanshiceping`.`interests` ;

CREATE TABLE IF NOT EXISTS `yuanshiceping`.`interests` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `initial` VARCHAR(20) NOT NULL DEFAULT '' COMMENT '英文首字母',
  `brief` VARCHAR(245) NOT NULL DEFAULT '' COMMENT '简介',
  `detail` VARCHAR(245) NOT NULL DEFAULT '' COMMENT '特点（详细报告中显示前两名）',
  `sort` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = '兴趣';


-- -----------------------------------------------------
-- Table `yuanshiceping`.`subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yuanshiceping`.`subjects` ;

CREATE TABLE IF NOT EXISTS `yuanshiceping`.`subjects` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT now(),
  `updated_at` TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '测评主题';


-- -----------------------------------------------------
-- Table `yuanshiceping`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yuanshiceping`.`categories` ;

CREATE TABLE IF NOT EXISTS `yuanshiceping`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `subject_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `is_multi` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1 COMMENT '是否为多个问题',
  `sort` SMALLINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '排序',
  PRIMARY KEY (`id`),
  INDEX `subject_id` (`subject_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = '分类 (A类 B类 C类)';


-- -----------------------------------------------------
-- Table `yuanshiceping`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yuanshiceping`.`questions` ;

CREATE TABLE IF NOT EXISTS `yuanshiceping`.`questions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `title` VARCHAR(200) NOT NULL DEFAULT '',
  `category_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `sort` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `category_id` (`category_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = '题目';


-- -----------------------------------------------------
-- Table `yuanshiceping`.`answers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yuanshiceping`.`answers` ;

CREATE TABLE IF NOT EXISTS `yuanshiceping`.`answers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `question_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `sort` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `question_id` (`question_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = '答案';


-- -----------------------------------------------------
-- Table `yuanshiceping`.`sub_questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `yuanshiceping`.`sub_questions` ;

CREATE TABLE IF NOT EXISTS `yuanshiceping`.`sub_questions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL DEFAULT '',
  `status` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `remark` VARCHAR(255) NOT NULL DEFAULT '',
  `title` VARCHAR(200) NOT NULL DEFAULT '',
  `question_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `sort` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `question_id` (`question_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COMMENT = '子问题';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
